spring.application.name=answer-service

server.port = 8082

# MongoDB
spring.data.mongodb.host=${HOST:localhost}
spring.data.mongodb.port=${DB_PORT:27017}
spring.data.mongodb.database=${DB_NAME:qs_answer}
spring.data.mongodb.auto-index-creation=true


jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


